# Generated by Django 6.0.3 on 2026-04-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_unique_customer_product_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='delivery',
            name='store_deliv_order_i_a0ef8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='store_order_custome_e65576_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='store_order_order_i_ec571c_idx',
        ),
        migrations.RemoveIndex(
            model_name='refund',
            name='store_refun_custome_494fa4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='store_revie_product_6484f3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='wishlist',
            name='store_wishl_custome_e838c4_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
