# Generated by Django 6.0.3 on 2026-04-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_deliveryaddress_paymentcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='label',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
