# Generated by Django 6.0.4 on 2026-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productreview_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('in-transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refund-requested', 'Refund Requested'), ('refunded', 'Refunded'), ('refund-rejected', 'Refund Rejected')], db_index=True, default='processing', max_length=20),
        ),
    ]
