# Generated by Django 5.2.13 on 2026-05-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_status'),
        ('store', '0011_wishlist'),
    ]

    operations = [
    ]
