# Generated by Django 6.0.5 on 2026-05-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_price'),
        ('store', '0015_category_is_active'),
    ]

    operations = [
    ]
